import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import "~/styles/globals.css";

import { MixpanelProvider } from "@/components/MixpanelProvider";
import { defaultLocale, locales, type Locale } from "@/i18n/config";
import { ReactNode } from "react";
import { QueryProvider } from "@/components/layout/query-client";
import { FlowParameterHandler } from "@/components/FlowParameterHandler";

export const metadata: Metadata = {
  title: "Vantum AI",
  description: "Generated by create next app",
};
interface Props {
  children: ReactNode;
  params: Promise<{ locale: string }>;
}

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;

  // Use the centralized config for supported locales
  const localeForProvider: Locale = locales.includes(locale as Locale)
    ? (locale as Locale)
    : defaultLocale;

  // Lấy messages - với try/catch để debug
  let messages;
  console.log("Requested locale:", locale);
  try {
    console.log("Loading messages for locale:", localeForProvider);
    messages = await getMessages({ locale: localeForProvider });
  } catch (error) {
    console.error("Error loading messages:", error);
    messages = {};
  }

  return (
    <NextIntlClientProvider messages={messages} locale={localeForProvider}>
      <MixpanelProvider>
        <FlowParameterHandler />
        {/* <AuthGuard> */}
          <QueryProvider>{children}</QueryProvider>
        {/* </AuthGuard> */}
      </MixpanelProvider>
    </NextIntlClientProvider>
  );
}
